addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "2.0.11")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.wartremover"         % "sbt-wartremover"     % "3.1.6")
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.timushev.sbt"        % "sbt-updates"         % "0.6.3")
addSbtPlugin("com.eed3si9n"            % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("org.scalaxb"             % "sbt-scalaxb"         % "1.12.0")
addSbtPlugin("org.playframework.twirl" % "sbt-twirl"           % "2.0.4")
