name: Fin Builds

on: [push, pull_request]

jobs:
  scala:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          sbt qa

      - name: Push Coverage Result
        uses: codecov/codecov-action@v3
        with:
          flags: scala
